<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e47eb7d3-f66c-4cb5-a60f-2950caccfc16</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebApplication2.Models\WebApplication2.Models.csproj" />
    <ProjectReference Include="..\WebApplication2.Models\WebApplication2.Services.csproj" />
    <ProjectReference Include="..\WebApplication2.Services\WebApplication2.Services.csproj" />
  </ItemGroup>

</Project>
